### ISSUE TITLE
Generator Registry issure

### ISSUE THREAD

**Issue by woorui** [go-kratos/swagger-api#5]
https://github.com/longXboy/grpc-gateway/blob/master/protoc-gen-openapiv2/generator/generator.go#L11
https://github.com/go-kratos/swagger-api/blob/main/openapiv2/service.go#L52
I found the`Generator.Registry` is not public to developer. I can't use api such as `reg.SetUseJSONNamesForFields(false)`, Making public to developer may be better?

**Comment by longXboy** [comment]
We have now moved the repo to https://github.com/go-kratos/grpc-gateway
,you can submit a pr

**Comment by woorui** [comment]
I submited https://github.com/go-kratos/grpc-gateway/pull/1/files

**Comment by longXboy** [comment]
> I submited here https://github.com/go-kratos/grpc-gateway/pull/1/files @longXboy

merged
